name: Install cbindgen
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        name: cbindgen
        path: prep
    - name: Setup cbindgen
      shell: bash
      run: |
        mkdir -p $HOME/.cargo/bin
        cp prep/cbindgen $HOME/.cargo/bin
        chmod 755 $HOME/.cargo/bin/cbindgen
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
