// This file is automatically generated. Do not edit.

use super::sys::FileContainer;

impl Default for FileContainer {
    fn default() -> Self {
        Self {
            head: std::ptr::null_mut(),
            tail: std::ptr::null_mut(),
        }
    }
}
