/* Copyright (C) 2017 Open Information Security Foundation
 *
 * You can copy, redistribute or modify this Program under the terms of
 * the GNU General Public License version 2 as published by the Free
 * Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */

/*
 * DO NOT EDIT. This file is automatically generated.
 */

#ifndef __RUST_DNS_LUA_H__
#define __RUST_DNS_LUA_H__

void rs_dns_lua_get_tx_id(lua_State * clua, RSDNSTransaction * tx);
int rs_dns_lua_get_rrname(lua_State * clua, RSDNSTransaction * tx);
int rs_dns_lua_get_query_table(lua_State * clua, RSDNSTransaction * tx);
int rs_dns_lua_get_answer_table(lua_State * clua, RSDNSTransaction * tx);
int rs_dns_lua_get_authority_table(lua_State * clua, RSDNSTransaction * tx);

#endif /* ! __RUST_DNS_LUA_H__ */
